version: "3.9"
services: 

  general-service:
    ports: 
      - "${GENERAL_SERVICE_OUTTER_PORT}:${GENERAL_SERVICE_INNER_PORT}"
    environment:
      PORT: "${GENERAL_SERVICE_INNER_PORT}"
      NODE_ENV: "${NODE_ENV}"
      NODEMAILER_SERVICE: "${NODEMAILER_SERVICE}"
      NODEMAILER_HOST: "${NODEMAILER_HOST}"
      NODEMAILER_USER: "${NODEMAILER_USER}"
      NODEMAILER_PASS: "${NODEMAILER_PASS}"
      MONGO_DB_URI: "${MONGO_DB_URI}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
      MONGO_DB_USER: "${MONGO_DB_USER}"
      MONGO_DB_PASS: "${MONGO_DB_PASS}"
      TEST_MONGO_DB_URL: "${TEST_MONGO_DB_URL}"
      TEST_MONGO_DB_NAME: "${TEST_MONGO_DB_NAME}"
      TEST_MONGO_DB_USER: "${TEST_MONGO_DB_USER}"
      TEST_MONGO_DB_PASS: "${TEST_MONGO_DB_PASS}"

  mongodb:
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  test-mongodb:
    ports:
      - "${TEST_MONGO_DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "${TEST_MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${TEST_MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${TEST_MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_USER: "${TEST_MONGO_DB_USER}"
      MONGO_DB_PASS: "${TEST_MONGO_DB_PASS}"


